limits:
  record:
    max_size: 20480000
    max_number: 3
    ttl: 0
  max_size: 20480000
  top_records_number: 100

redis:
  host: redis
  port: 6379
  queueName: "pendingPages"

server:
  port: 8000