limits:
  record:
    max_size: 20480000
    ttl: "2h"
  max_count: 1000
  max_size: 20480000

cache:
  expiration_interval: "1m"
  top_records_count: 100

redis:
  host: redis
  port: 6379

server:
  port: 8000