limits:
  record:
    max_size: 40960000
    max_number: 1000
    ttl: "2h"
  max_size: 20480000

cache:
  ttl_eviction_interval: "30m"
  top_records_number: 100

redis:
  host: redis
  port: 6379
  queueName: "pendingPages"

server:
  port: 8000